namespace StockRestAPI.Models
{
    public class DailyBar
    {
        public int Id { get; set; }  // This will be auto-generated by the database
        public string Symbol { get; set; }  // For example, "AAPL"
        public DateTime Timestamp { get; set; }  // This will be mapped from 't' (ISO 8601 datetime)
        public double Open { get; set; }  // From 'o'
        public double High { get; set; }  // From 'h'
        public double Low { get; set; }  // From 'l'
        public double Close { get; set; }  // From 'c'
        public long Volume { get; set; }  // From 'v'
        public long TradeCount { get; set; }  // From 'n'
        public double VW { get; set; }  // From 'vw'

        // Parameterless constructor for EF
        public DailyBar() { }

    }

}
